---
title: "project_1"
output: html_document
author: Maya Pottiger
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# running libraries to use

library(tidyverse)
library(janitor)
library(arcos)
library(scales)
library(ggrepel)
library(tidycensus)
library(dplyr)
library(rvest)
library(mapview)

```


```{r}

# In our last in-class lab, we wrote code to rank zip codes based on the median income in a county and how many pills per person the county received from 2006-2012. At the end of the lab, I ran the data for all of the counties in the country. Right now, I am going to run the data for the individual towns within Anne Arundel County. I've looked at the rankings before, but now I will visualize them.

# This is from lab_O7. I requested my own key from the census: 

key <- "uO4EK6I"

census_api_key("366af81ca42273ae67ad0729766f54f041bd300d")


# The following graf is from lab_07:

# Store a table with the median household income value for each county using the get_acs() function.  ACS is short for American Community Survey, one of two main census products. In the table that's loaded in, the :estimate" is the median household income for that county, averaged over 5 years ending in 2006. 

county_median_household_income <- get_acs(geography = "county", variables = c("B19013_001"), survey="acs5", year = 2012)

# How did I get the variables? I pulled in a table from the tidycensus package that lists all of the thousands of variables available through the census. Load the table below and view it.  Use filters in the R Viewer window to find things you might want to use later. You can also find table and variable numbers at https://data.census.gov/cedsci/.

acs_variables <- load_variables(2012, "acs5", cache = TRUE)

# Filter just for Maryland counties

md_county_median_household_income <- county_median_household_income %>%
  filter(str_detect(NAME, ", Maryland"))


```
```{r}
arcos_county_pills_per_year <- summarized_county_annual(key = key) %>%
  clean_names()

```

```{r}

maryland_pills_2012 <- arcos_county_pills_per_year %>%
  filter(buyer_state == "MD", year=="2012") %>%
  select(buyer_county, year, dosage_unit, countyfips)
```

```{r}
maryland_population_2012 <- county_population(key = key) %>%
  clean_names() %>%
  filter(buyer_state == "MD", year=="2012") %>%
  select(county_name, population, countyfips)

```

```{r}
maryland_2012 <- maryland_pills_2012 %>%
  inner_join(maryland_population_2012, by=("countyfips")) %>%
  select(buyer_county, dosage_unit, population, countyfips)

```

```{r}

md_2012_pills_per_person <- maryland_2012 %>%
  select(buyer_county, dosage_unit, population, countyfips) %>%
  mutate(pills_per_person = (dosage_unit / population))

```

```{r}

md_2012_pills_per_person <- as.data.frame(md_2012_pills_per_person)

md_2012_pills_per_person %>%
  select(-buyer_county, -countyfips) %>%
  correlate()

```

```{r}

md_county_median_household_income <- md_county_median_household_income %>%
  mutate(countyfips = GEOID)

```

```{r}

md_2012_household_pills <- md_county_median_household_income %>%
  inner_join(md_2012_pills_per_person, by=("countyfips")) %>%
  arrange(desc(dosage_unit))

# From this, we learn that Anne Arundel County ranks third in the most pills received in the state of Maryland.

```

```{r}

md_2012_household_pills %>%
  arrange(desc(estimate))

# Anne Arundel County is the fifth-richest county in Maryland. Baltimore County, which received the most pills, ranks 12th. The poorest county in Maryland, Allegany County, ranks 12th for the most number of pills received. In Maryland, there isn't a direct correlation between median household income and number of pills received.

```

```{r}

md_2012_household_pills <- md_county_median_household_income %>%
  inner_join(md_2012_pills_per_person, by=("countyfips")) %>%
  arrange(desc(pills_per_person))

# Kent County had the highest pills per person in the state of Maryland. Anne Arundel County is not even in the top 10. Allegany, the poorest county, ranks second. Baltimore County, which had the most pills, ranks 8th.

```

```{r}

glimpse(md_county_median_household_income) %>%
  arrange(desc(estimate))

# Howard County has the highest medium income in Maryland. Anne Arundel County ranks fifth. This surprised me.

```

```{r}

# I want to rank the towns in Anne Arundel County based on dosage_unit.

arundel_pharmacies <- total_pharmacies_county(county="Anne Arundel", state="MD", key = key)

```

```{r}

arundel_pharmacies %>%
  group_by(buyer_city) %>%
  summarise(total_pills = sum(total_dosage_unit)) %>%
  arrange(desc(total_pills))

# Glen Burnie received the most pills... Where does Glen Burnie fall in median household income? 

```

```{r}

# Where does Glen Burnie fall in terms of median household income in Anne Arundel County?

aac_raw <- county_raw(county="Anne Arundel", state="MD", key = key)

aac_pharm_tracts <- pharm_tracts(county="Anne Arundel", state="MD", key = key)


```

```{r}

aac_pharms <- aac_raw %>%
  inner_join(aac_pharm_tracts, by=c("BUYER_DEA_NO")) %>%
  select(BUYER_CITY, BUYER_ZIP, DOSAGE_UNIT, TRACTCE) %>%
  group_by(BUYER_CITY, BUYER_ZIP, TRACTCE) %>%
  summarise()

# I was able to group the city, zip and tract to see how these numbers correspond. Annapolis is the only city that had two zip codes. This will be helpful going forward if try to break down DOSAGE_UNIT by zip code.

```

```{r}

# v1 <- load_variables(year='2006', dataset='aac_pharms', cache = FALSE, key=key)

# I was trying to load the variables so I could look up median household income, but I kept getting "open.connection(x, "rb") : HTTP error 404." I downloaded rvest, but it didn't help. I also got a warning message about closing an unused connectin.

```

```{r}

test <- get_acs(geography = "tract", variables = "B19013_001",
                state = "TX", county = "Tarrant", geometry = TRUE)


```

```{r}

aac_monthly <- summarized_county_monthly(county="Anne Arundel", state="MD", key = key)

aac_monthly %>%
  arrange(desc(DOSAGE_UNIT))

# January 2006 was significantly lower than the rest of the range. 2011 and 2012 were the higher income years for pills. 

```

```{r}

aac_buyer <- combined_buyer_annual(county="Anne Arundel", state="MD", key = key)

aac_buyer %>%
  group_by(BUYER_DEA_NO, year) %>%
  summarise(DOSAGE_UNIT) %>%
  arrange(desc(DOSAGE_UNIT))

# Two years in a row, the same buyer received the highest number of pills, and it was significantly higher than the other numbers.

```

```{r}

aac_buyer_addresses <- buyer_addresses(county="Anne Arundel", state="MD", key = key)

# I searched the BUYER_DEA_NO from the previous codeblock into this data set. The buyer is Crain Towers Pharmacy, located in Glen Burnie. It is also the site of a National Spine & Pain Center, so that definitely adds legitimacy, but how much?

```

```{r}

aac_buyer_details <- combined_buyer_monthly(county="Anne Arundel", state="MD", year="2006", key = key)

```

```{r}

country_pills_2012 <- arcos_county_pills_per_year %>%
  filter(year=="2006") %>%
  select(buyer_county, buyer_state, year, dosage_unit) %>%
  arrange(desc(dosage_unit))

# Where Anne Arundel County ranks in the country by year:
# 2006: 108, with 14376402 pills
# 2007: 112, with 15836968 pills
# 2008: 124, with 16671976 pills
# 2009: 117, with 18239025 pills
# 2010: 124, with 19151845 pills
# 2011: 126, with 20354650 pills
# 2012: 125, with 19928983 pills

# Anne Arundel County ranked the highest in 2006, at 108 with a total 14,376,402 pills received.

```

```{r}

aac_buyer %>%
  filter(year=="2006") %>%
  select(BUYER_DEA_NO, BUYER_COUNTY, BUYER_STATE, year, DOSAGE_UNIT) %>%
  arrange(desc(DOSAGE_UNIT))

# The top buyer in 2006 was Crain Towers Pharmacy. It was responsible for about 3.386% of the pills sent to Anne Arundel County in 2006.

```

```{r}

country_income_05_09 <- get_acs(geography = "county", variables = c("B19013_001"), year = 2009) %>%
  arrange(desc(estimate))

# From 2005-2009, Anne Arundel County ranked 34th in median household income in the country. This dataset has a large margin of error.

```

```{r}

country_income_08_12 <- get_acs(geography = "county", variables = c("B19013_001"), year = 2012) %>%
  arrange(desc(estimate))

# From 2008-2012, Anne Arundel County moved up in rank to 27th in median household income in the country. 

```

```{r}

# country_income_08_12 <- get_acs(geography = "tract", variables = c("B19013_001"), survey="acs5", year = 2012) %>%
#  arrange(desc(estimate))

# Per a Data Camp tip sheet, I tried setting the geography as 'tract,' since I found those in a previous codeblock. But it said my API call had errors in that there was an unknown/unsupported geography heirarchy. When I tried to write county and tract, it said that I had the same argument twice, both of which returned information. So I'm not sure how to get the tract to return information. 

```


```{r}

aac_tract_income <- get_acs(geography = "tract", variables = "B19013_001",
                state = "MD", county = "Anne Arundel", geometry = TRUE)

# I was able to use this to get the median household incomes based on tract. However, these tract numbers don't match up with the TRACTCE numbers I previously found.

```

```{r}

md_population <- state_population(state="MD", key = key)

# Maryland had its highest ranking of pills received in 2006, which is when the population was lowest in the 2006-2012 time period we are analyzing.

```

```{r}

country_income_08_12 <- country_income_08_12 %>%
  mutate(countyfips = GEOID)

```

```{r}
# country_income_pills <- country_income_08_12 %>%
#  inner_join(country_pills_2012, by=("countyfips")) %>%
#  arrange(desc(dosage_unit))
```

```{r}
# ggplot(country_income_pills) +
#  geom_point(aes(dosage_unit, estimate)) +
#  labs(title="Dosage Unit by Median Income", caption = "Source: DEA ARCOS database, via Washington Post", fill="buyer_county") +
#  scale_y_continuous(labels = comma) +
#  scale_x_continuous(labels = comma) + 
#  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
#  geom_smooth(aes(dosage_unit, estimate), method = "lm", se = FALSE)

# From this, I can see that the county with the highest dosage unit was under the country's average for median household income.

```

```{r}

v17 <- load_variables(2017, "acs5", cache = TRUE)

x <- v17 %>%
  filter(str_detect(concept, "EMPLOY"))

```

```{r}

# This should tell me the employment status of the labor force in Anne Arundel County in 2012. B23025_002

aac_labor_force <- get_acs(geography = "county", variables = c("B23025_002"), year = 2012)

# From the 2008-2012 census data, there were 303,444 people in the workforce.  

```

```{r}

# This is the breakdown of black people. B02001_003

aac_black <- get_acs(geography = "county", variables = c("B02001_003"), year = 2012)

# In Anne Arundel County in 2012, there were 82,542 black people.

```

```{r}

# This is the breakdown of asian people. B02001_005

aac_asian <- get_acs(geography = "county", variables = c("B02001_005"), year = 2012)

# In 2012, there were 18,618 asian people in Anne Arundel County.

```

```{r}

# This will give a breakdown of the white population. B02001_002

aac_white <- get_acs(geography = "county", variables = c("B02001_002"), year = 2012)

# In Anne Arundel County in 2012, there were 408,521 white people.

```

```{r}

aac_population_2012 <- county_population(state = "MD", county = "Anne Arundel", key = key)

# In 2012, Anne Arundel County had a population of 538,473 people. Based on my three previous code blocks, Anne Arundel County is largely white.

```

```{r}

aac_race <- get_acs(geography = "county", variables = c("B02001_001"), year = 2012)

# This gives the same number as the county_population I did in the previous code block.

```

```{r}

aac_all_races <- aac_white %>%
  inner_join(aac_black, by=("GEOID"))

```

```{r}

poverty_rate <- get_acs(geography = "county", variables = c("B06012_002"), year = 2012)

```

```{r}

race <- get_acs(geography = "county", variables = c("B02001_001"), year = 2012)

```

```{r}

pop_poverty <- race %>%
  inner_join(poverty_rate, by=c("GEOID")) %>%
  select(GEOID, NAME.x, estimate.x, estimate.y) %>%
  mutate(poverty_rate = estimate.y/estimate.x *100) 

# I tried several times to rename the columns: estimate.x to "population" and estimate.y to "poverty. Neither the rename nor mutate functions worked. I tried colnames, as well. It kept telling me the object wasn't found, those column types weren't supported or spouting random error messages. I'm not sure my dplyr is properly installed.

# With this, I joined the population and poverty tables and created a new column to calculate the poverty rate in every county in the country (except Puerto Rico, which is not included in this dataset).

```

```{r}

# mapview(pop_poverty, xcol = "estimate.x", ycol = "estimate.y", legend = TRUE)

# Can I not map this out because the data is by county? And there isn't a specific column for state? Is there an easy fix to this?

```

```{r}

white_pop <- aac_white %>%
  inner_join(race, by="GEOID") %>%
  select(GEOID, NAME.x, estimate.x, estimate.y) %>%
  mutate(white_percentage = estimate.x/estimate.y *100)

# With this, I found the number of people who identify as white and then compared that to the county's total population to find the percentage of white residents in each county. Much of the research says the opioid crisis largely impacted the white population, and I want to see if that's true. The next step will be to compare this to the dosage unit.

```

```{r}

white_poverty <- pop_poverty %>%
  inner_join(white_pop, by="GEOID") %>%
  select(GEOID, NAME.x.x, poverty_rate, white_percentage)

```

```{r}

ggplot(white_poverty) +
  geom_point(aes(poverty_rate, white_percentage)) +
  labs(title="HED", caption = "Source: DEA ARCOS database, via Washington Post", fill="") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(aes(poverty_rate, white_percentage), method = "lm", se = FALSE)
  
# This isn't perfect, but from this graph, we can see that the areas with a higher white percentage have a much lower poverty rate. Now I need to add in dosage unit and unemployment. 

```

```{r}

# I need to find the total population of men in the workforce, then the total number of women in the workforce. Then I will add those together and divide it by the total population, and this will give me a (very) rough idea of what the unemployment rate is. 

# The variable I'm using is unemployment based on health care enrollment. I want to see if this works. B27011_008

unemployment_by_healthcare <- get_acs(geography = "county", variables = c("B27011_008"), year = 2012)

```

```{r}

total_unemplyment <- unemployment_by_healthcare %>%
  inner_join(race, by="GEOID") %>%
  select(GEOID, NAME.x, estimate.x, estimate.y) %>%
  mutate(unemployment_rate = estimate.x/estimate.y *100)

# These numbers aren't as outrageous as I thought they would be, so I could see this being fairly accurate. 

```

```{r}

everything <- total_unemplyment %>%
  inner_join(white_poverty, by="GEOID") %>%
  select(GEOID, NAME.x, unemployment_rate, poverty_rate, white_percentage)

# So far, I don't see too many shocking trends. The places with the highest poverty rate generally have a lower white population. Poverty and unemployment are generally similar. I need to add in dosage unit to get the key piece of my analysis, but I don't know how to get dosage unit for every county.

```

```{r}

pills <- summarized_county_annual(key = key)

```

```{r}

pills_population <- pills %>%
  inner_join(race, by=c("countyfips" = "GEOID")) %>%
  group_by(BUYER_COUNTY, BUYER_STATE, countyfips) %>%
  summarise(total_pills = sum(DOSAGE_UNIT), total_population = sum(estimate)) %>%
  mutate(pills_per_person = total_pills/total_population) %>%
  inner_join(everything, by=c("countyfips" = "GEOID"))

```

```{r}

county_geodata_shifted <- get_acs(geography = "county",
              variables = "B01001_001", geometry = TRUE, shift_geo = TRUE)


pills_population_map <- county_geodata_shifted %>%
  inner_join(pills_population, by=c("GEOID" = "countyfips"))

```

```{r}

mapview(pills_population_map, zcol = "pills_per_person", legend = TRUE)

```

```{r}

ggplot(pills_population) +
  geom_point(aes(total_pills, total_population)) +
  labs(title="HED", caption = "Source: DEA ARCOS database, via Washington Post", fill="") +
  scale_y_continuous(labels = comma) +
  scale_x_continuous(labels = comma) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  geom_smooth(aes(total_pills, total_population), method = "lm", se = FALSE)

```

```{r}

# install.packages("corrr")
# install.packages('lsr')
library(lsr)

```

```{r}

library(corrr)

#glimpse(pills_population)

pills_population <- as.data.frame(pills_population)

pills_population %>%
  select(-BUYER_COUNTY, -BUYER_STATE, -countyfips, -NAME.x) %>%
  correlate()


# The correlate function allows me to quickly see the relationships between each of these factors without creating a ton of scatter plots. There isn't too high of a correlation between anything I'm looking at, but the highest correlations are between total pills and white percentage, and poverty rate and pills per person.

```


